### ISSUE TITLE
Laravel 10 upgrade issue

### ISSUE THREAD

**Issue by Jyothy-K-A** [pawlox/video-thumbnail#12]
When upgrade to laravel 10 from 9
It shows 
- Root composer.json requires pawlox/video-thumbnail ^4.0.0 -> satisfiable by pawlox/video-thumbnail[v4.0.0].
my composer file includes this "pawlox/video-thumbnail": "^4.0.0",

**Comment by sanaz1992** [comment]
i get this error when install this package! can you help me?

 Problem 1
    - Root composer.json requires pawlox/video-thumbnail 4.0.0 -> satisfiable by pawlox/video-thumbnail[v4.0.0].    - pawlox/video-thumbnail v4.0.0 requires illuminate/support ^9.0 -> found illuminate/support[v9.0.0, ..., v9.52.15] but these were not loaded, likely because it conflicts with another require.
