### ISSUE TITLE
Create thumbnail not working

### ISSUE THREAD

**Issue by Darshit-Soni** [pawlox/video-thumbnail#3]
install your package from here : https://packagist.org/packages/pawlox/video-thumbnail
i also install ffmpeg.
here is my code to create thumbail 
VideoThumbnail::createThumbnail('../public/uploads/original/20180124_125005.mp4', '../public/uploads/thumbnail/', 'movie.png', 5, 500, 500);

But thumbnail not generate

**Comment by pawlox** [comment]
Hello,
I think that your paths may be wrong, someone had similar problems. Try changing them to e.g. public_path('uploads/original/20180124_125005.mp4'), so your code will look like this:
`VideoThumbnail::createThumbnail(public_path('uploads/original/20180124_125005.mp4'), public_path('uploads/thumbnail/'), 'movie.png', 5, 500, 500);`

**Comment by Darshit-Soni** [comment]
Thanks @pawlox 
Now it's working.
