### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by SergeiLomako** [pawlox/video-thumbnail#4]
Hi! Example VideoThumbnail::createThumbnail(public_path('files/movie.mp4'), public_path('files/thumbs/'), 'movie.jpg', 2, 1920, 1080) not working (method createThumbnail not static)

**Comment by pawlox** [comment]
Hello,
What version of Laravel have you got? Did you add service provider and VideoThumbnail facade alias to config/app.php file?

**Comment by SergeiLomako** [comment]
Laravel 5.5 . Alias and service provider add.

  $thumbnail = new VideoThumbnail();
  $thumbnail->createThumbnail(public_path(env('VIDEO_PATH'). $input['video']), public_path(env('VIDEO_THUMBNAIL_PATH')),
                $input['thumbnail'], 20, 150, 150);
It's working

**Comment by pawlox** [comment]
Thanks for reporting this issue, I will look into it and give you feedback if I find something.

**Comment by justinesguerra** [comment]
Hi there,

i'm trying to display to view.

**HomeController.php**
$video = VideoThumbnail::createThumbnail(public_path('files/movie.mp4'), public_path('files/thumbs/'), 'movie.jpg', 2, 1920, 1080);

**home.blade.php**
{{$video}} or {!!$video!!} is not working

**Comment by pawlox** [comment]
@justinesguerra Hi, that's becouse VideoThumbnail::createThumbnail() methods returns VideoThumbnail class object, not path to the thumbnail. You can get path to your thumbnail (if it is generated correctly) by using for example asset() helper like this:

`asset('files/thumbs/movie.jpg')`

**Comment by Sallar49** [comment]
Hello Pawlox,
I am also trying your example it return an object but does not store image.

`Pawlox\VideoThumbnail\VideoThumbnail {#1289 ▼
  #FFMpeg: null
  #videoObject: null
  #videoURL: "https://www.w3schools.com/html/mov_bbb.mp4#t=0.5"
  #storageURL: "C:\xampp\htdocs\laravel7\public\files/thumb/"
  #thumbName: "Dummy.jpg"
  #fullFile: "C:\xampp\htdocs\laravel7\public\files/thumb//Dummy.jpg"
  #height: 480
  #width: 640
  #screenShotTime: 3
}`
