### ISSUE TITLE
Store thumbnail to AWS S3

### ISSUE THREAD

**Issue by ghost** [pawlox/video-thumbnail#6]
Could you please let me know the steps to generate thumb with AWS S3 as storage ?

**Comment by pawlox** [comment]
I made some research and I think that this functionality is out of this package scope. It uses ffmpeg under the hood, and this tool needs some local path to save to (there is some HLS option, but I don't know if it works for image files). If you're using Linux system you may want to try mounting S3 Bucket to your system - https://tecadmin.net/mount-s3-bucket-centosrhel-ubuntu-using-s3fs/ to save directly to it or generate thumbnail locally and then upload it to S3 in second step.
